### ISSUE TITLE
v128 SOCKS change

### ISSUE THREAD

**Issue by Tiagoquix** [ghacksuserjs/ghacks-user.js#1863]
https://www.mozilla.org/en-US/firefox/128.0beta/releasenotes/

> Firefox now proxies DNS by default when using SOCKS v5, avoiding leaking DNS queries to the network when using SOCKS v5 proxies.

I believe it affects the following pref:

https://github.com/arkenfox/user.js/blob/23caf6961483e0e55544cd4f3594734d0aa35cf0/user.js#L254-L258

I think it will be true by default in the future

**Comment by rusty-snake** [comment]
https://searchfox.org/mozilla-central/source/modules/libpref/init/StaticPrefList.yaml#12726

```yaml
# Whether the SOCKS5 proxy should be in charge of DNS resolution. Making it a
# SOCKS5h proxy by convention
- name: network.proxy.socks5_remote_dns
  type: RelaxedAtomicBool
  value: true
  mirror: always

# Whether the SOCKS4 proxy should be in charge of DNS resolution. Making it a
# SOCKS4a proxy.
- name: network.proxy.socks_remote_dns
  type: RelaxedAtomicBool
  value: false
  mirror: always

```
